# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b936438f588715be624f6c0a76f7c5de6541cfafd1649120187658f32a7ea2bf2defecae6e98032d8c7912f569ddae20dc9f95b90e1a4aca49d6e002d732977

test:
  secret_key_base: 2385aeb04b9f29cd474715ffdf8d6adecf29a20b1422df5f3456a2f30d8acab96ba986b1ffb59c285f2650dec7e080011891094ba7b64c9f210aa42261afcd01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
